services:
  - type: web
    name: qr-generator
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: BASE_URL
        value: ""
      - key: ADMIN_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false

